Update customdeploy.yml

diff --git a/.github/workflows/customdeploy.yml b/.github/workflows/customdeploy.yml
--- a/.github/workflows/customdeploy.yml
+++ b/.github/workflows/customdeploy.yml
@@ -53,11 +53,8 @@ jobs:
           source $HOME/miniconda3/etc/profile.d/conda.sh
           conda activate myenv
           sleep 10  # Adding a 10-second delay to ensure activation
-          source /home/duttvnyn/miniconda3/etc/profile.d/conda.sh  # Additional sourcing
-          conda activate myenv  # Additional activation
-          current_env=$(conda info --envs | grep '*' | awk '{print $1}')
-          if [ "$current_env" != "myenv" ]; then
-            echo "Virtual environment not activated"
+          if [ $? -ne 0 ]; then
+            echo "Failed to activate virtual environment"
             exit 1
           fi
           conda install pip -y
@@ -132,8 +129,6 @@ jobs:
             source /home/duttvnyn/miniconda3/etc/profile.d/conda.sh
             conda activate myenv
             sleep 10  # Adding a 10-second delay to ensure activation
-            source /home/duttvnyn/miniconda3/etc/profile.d/conda.sh  # Additional sourcing
-            conda activate myenv  # Additional activation
             current_env=$(conda info --envs | grep '*' | awk '{print $1}')
             if [ "$current_env" != "myenv" ]; then
               echo "Virtual environment not activated"
@@ -151,8 +146,8 @@ jobs:
               echo "Failed to run migrations"
               exit 1
             fi
-            # Restart HTTP server using Apache httpd command directly
-            sudo /usr/local/apache2/bin/apachectl restart
+            # Ensure the full path to the service command
+            /usr/sbin/service httpd restart
             if [ $? -ne 0 ]; then
               echo "Failed to restart HTTP server"
               exit 1
